/**
 * Server-side mirror of /src/config/products.js
 *
 * AUTO-GENERATED by scripts/sync-products.mjs. Do not edit by hand.
 * Run `npm run sync:products` (or `npm run build`, which calls it)
 * after changing src/config/products.js.
 *
 * Netlify Functions run in a Node context separate from /src and can't
 * import the ESM source directly, so this CommonJS mirror is what the
 * checkout and webhook functions read at runtime.
 */

const PRODUCTS = [
  {
    "slug": "va-toolkit",
    "name": "VA Benefits Decision Toolkit",
    "tagline": "Navigate your VA claim like the pros — without paying 25% of your retro to one.",
    "priceCents": 3900,
    "currency": "usd",
    "recurring": null,
    "stripeProductName": "VVV Digitals — Educational Toolkit",
    "pdfBundle": [
      "hlr-walkthrough.pdf",
      "supplemental-claim-walkthrough.pdf",
      "effective-date-playbook.pdf",
      "decision-tree-cheat-sheet.pdf",
      "evidence-tracker.pdf",
      "va-terms-glossary.pdf"
    ],
    "toolAccess": "/tools/va-calculator",
    "status": "live"
  }
];

function getProductBySlug(slug) {
  return PRODUCTS.find((p) => p.slug === slug && p.status === 'live');
}

function getStripeName(product) {
  return product.stripeProductName || product.name;
}

module.exports = { PRODUCTS, products: PRODUCTS, getProductBySlug, getStripeName };
